### ISSUE TITLE
runexample.mac gets stuck

### ISSUE THREAD

**Issue by cipriangal** [JeffersonLab/remoll#436]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): develop
- revision (HEAD for most recent): f17d50483f084f89b8772f45ad4431c16e29abc5
- OS or system: jlab cev 2.3
- Special ROOT or Geant4 versions? : g4.10.04.p02

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. get a fresh copy of develop branch
2. build
3. run: "build/remoll macros/runexample.mac"

### Expected Result: (what do you expect when you execute the steps above)
it runs 100 events in a reasonable time.

### Actual Result: (what do you get when you execute the steps above)
it seems to get stuck in first few events (it sometimes went to event 4 and it got stuck). 
![image](https://user-images.githubusercontent.com/8987591/106035653-5f040700-60a2-11eb-9f9d-f3d9cd5eaa93.png)
This figure shows remoll spinning it's wheels for 5 minutes. no error to clearly debug. The navigator error for the "logicMother_PV" sometimes is replaced by "donutSystem_logical_PV". If I comment out the donutSystem in the gdml this still happens.

**Comment by wdconinc** [comment]
JLab softenv.sh 2.4 does not have this issue. I can confirm it occurs on 2.3. Still needs a fix, though.

gdb tells me that it is stuck in some voxel routines, i.e. geometry-related.

I was able to reduce the geometry to only include the target volume and the "dump" volume in the hall daughter, and that still caused the issue. However, just commenting out the "dump" volume didn't fix it.

`/tracking/verbose 1` tells me that the issue is with electrons undergoing 'weird' eIoni processes in the cylwall:
```
*********************************************************************************************************
* G4Track Information:   Particle = e-,   Track ID = 479,   Parent ID = 103
*********************************************************************************************************

Step#    X(mm)    Y(mm)    Z(mm) KinE(MeV)  dE(MeV) StepLeng TrackLeng  NextVolume ProcName
    0 1.39e+03     -905 2.65e+04     0.903        0        0         0     cylwall initStep
    1 1.39e+03     -905 2.65e+04     0.903        0 -1.68e-20 -1.68e-20     cylwall eIoni
    2 1.39e+03     -905 2.65e+04     0.903        0 -1.68e-20 -3.36e-20     cylwall eIoni
    3 1.39e+03     -905 2.65e+04     0.903        0 -1.68e-20 -5.04e-20     cylwall eIoni
    4 1.39e+03     -905 2.65e+04     0.903        0 -1.68e-20 -6.72e-20     cylwall eIoni
    5 1.39e+03     -905 2.65e+04     0.903        0 -1.68e-20 -8.41e-20     cylwall eIoni
...
625310 1.39e+03     -905 2.65e+04     0.903        0 -1.68e-20 -1.05e-14     cylwall eIoni
625311 1.39e+03     -905 2.65e+04     0.903        0 -1.68e-20 -1.05e-14     cylwall eIoni
625312 1.39e+03     -905 2.65e+04     0.903        0 -1.68e-20 -1.05e-14     cylwall eIoni
625313 1.39e+03     -905 2.65e+04     0.903        0 -1.68e-20 -1.05e-14     cylwall eIoni
625314 1.39e+03     -905 2.65e+04     0.903        0 -1.68e-20 -1.05e-14     cylwall eIoni
625315 1.39e+03     -905 2.65e+04     0.903        0 -1.68e-20 -1.05e-14     cylwall eIoni
625316 1.39e+03     -905 2.65e+04     0.903        0 -1.68e-20 -1.05e-14     cylwall eIoni
625317 1.39e+03     -905 2.65e+04     0.903        0 -1.68e-20 -1.05e-14     cylwall eIoni
625318 1.39e+03     -905 2.65e+04     0.903        0 -1.68e-20 -1.05e-14     cylwall eIoni
...
```
i.e. track stuck.

What's at that XYZ coordinate, @cipriangal? You are familiar with the cylwall. Is that where I made the hole for the DS beamline to the dump?

**Comment by cipriangal** [comment]
That looks really close to the change you made. I suspect something odd is happening there. My plan for today is to try and move the hall-wall detector to the parallel world; which I guess should fix this since it won't have any more subtractions.

**Comment by wdconinc** [comment]
There will still be subtraction, I fear. The detector in the parallel world doesn't solve the problem of the beampipe/dump interface which is flat, but the hall world is round.

**Comment by wdconinc** [comment]
Yeah, reverting 210391f8363140a915b004312c11343005a9a7fd (by using `boxHallMother_1` as mother volume instead) doesn't fix the issue.

**Comment by wdconinc** [comment]
As far back as a2e74c75dfdc9a9a403eab0aad6eb5f09ce1944c (September 2020) this has been an issue.

**Comment by wdconinc** [comment]
As far back as 3ff123201ddda35f919ca29574c93a251e789067 (June 2020).

**Comment by wdconinc** [comment]
@cipriangal I have not able to find a unique cause (when we find one offending commit with jlabce 2.3 on one system, then even on a different system it may not actually fail). There are currently no docker containers to do online integration testing with jlabce 2.4 (and it is unlikely that there will be any soon, as JLab it moving away from jlabce in favor of spack). In order to do the online integration testing, we will also be moving over to spack. So, I propose that I send an email around, tell everying about all the great reasons for upgrading to 2.4, and we close this bug report (admittedly without fixing or even understanding what the issue is).

**Comment by cipriangal** [comment]
Sounds like the right way to move forward.
